# Generated by Django 5.2 on 2025-04-09 14:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование статьи')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistic.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'unique_together': {('name', 'company')},
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Номер')),
                ('status', models.CharField(choices=[('at_warehouse', 'Формируется на складе'), ('document_preparation', 'Подготовка документов'), ('departed', 'Вышел со склада'), ('border_crossing', 'Прохождение границы'), ('customs_clearance', 'Таможенная очистка'), ('on_way_to_customs', 'В пути на таможню'), ('on_way_to_warehouse', 'В пути на склад выгрузки'), ('at_unloading_warehouse', 'На складе выгрузки'), ('done', 'Завершен')], default='at_warehouse', max_length=50, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistic.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Отправка',
                'verbose_name_plural': 'Отправки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Номер')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('warehouse_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер на складе')),
                ('col_mest', models.FloatField(blank=True, null=True, verbose_name='Количество мест')),
                ('declared_weight', models.FloatField(blank=True, null=True, verbose_name='Заявленный вес')),
                ('declared_volume', models.FloatField(blank=True, null=True, verbose_name='Заявленный объем')),
                ('actual_weight', models.FloatField(blank=True, null=True, verbose_name='Фактический вес')),
                ('actual_volume', models.FloatField(blank=True, null=True, verbose_name='Фактический объем')),
                ('rate', models.TextField(blank=True, null=True, verbose_name='Ставка')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('new', 'Новая заявка'), ('expected', 'Ожидается на складе'), ('on_warehouse', 'Формируется'), ('in_progress', 'В работе'), ('ready', 'Готово к выдаче'), ('delivered', 'Выдано')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistic.company', verbose_name='Компания')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistic.shipment', verbose_name='Отправка')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('euro_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Курс Евро')),
                ('usd_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Курс Доллара')),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calculation', to='logistic.shipment', verbose_name='Отправка')),
            ],
            options={
                'verbose_name': 'Расчет отправки',
                'verbose_name_plural': 'Расчеты отправок',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('user_group', models.CharField(choices=[('superuser', 'Суперпользователь'), ('admin', 'Администратор'), ('boss', 'Руководитель'), ('manager', 'Менеджер'), ('warehouse', 'Склад'), ('client', 'Клиент')], max_length=50, verbose_name='Группа пользователя')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistic.company', verbose_name='Компания')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
                'permissions': [('view_own_company_data', 'Может просматривать данные своей компании'), ('edit_own_company_data', 'Может редактировать данные своей компании')],
            },
        ),
        migrations.CreateModel(
            name='ShipmentFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название папки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='logistic.shipment', verbose_name='Отправка')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistic.userprofile', verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Папка отправки',
                'verbose_name_plural': 'Папки отправок',
            },
        ),
        migrations.CreateModel(
            name='ShipmentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=255, verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='logistic.shipment', verbose_name='Отправка')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='logistic.shipmentfolder', verbose_name='Папка')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistic.userprofile', verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Файл отправки',
                'verbose_name_plural': 'Файлы отправок',
            },
        ),
        migrations.AddField(
            model_name='shipment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shipments', to='logistic.userprofile', verbose_name='Создал'),
        ),
        migrations.CreateModel(
            name='RequestFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=255, verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='logistic.request', verbose_name='Заявка')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistic.userprofile', verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Файл заявки',
                'verbose_name_plural': 'Файлы заявок',
            },
        ),
        migrations.AddField(
            model_name='request',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_requests', to='logistic.userprofile', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='request',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_requests', to='logistic.userprofile', verbose_name='Менеджер'),
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('operation_type', models.CharField(choices=[('in', 'Входящий'), ('out', 'Исходящий')], max_length=10, verbose_name='Тип операции')),
                ('payment_date', models.DateField(verbose_name='Дата оплаты')),
                ('document_type', models.CharField(choices=[('bill', 'Счёт'), ('payment', 'Оплата')], max_length=10, verbose_name='Тип документа')),
                ('currency', models.CharField(choices=[('rub', 'Рубль'), ('rubbn', 'Безнал'), ('rubnds', 'НДС'), ('eur', 'Евро'), ('usd', 'Доллар')], max_length=10, verbose_name='Валюта')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачен')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistic.article', verbose_name='Статья')),
                ('basis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistic.finance', verbose_name='Основание')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistic.company', verbose_name='Компания')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Контрагент')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistic.request', verbose_name='Заявка')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistic.shipment', verbose_name='Отправление')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_finances', to='logistic.userprofile', verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Финансовая операция',
                'verbose_name_plural': 'Финансовые операции',
                'ordering': ['-created_at'],
            },
        ),
    ]
