# Generated by Django 5.2 on 2025-04-12 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Код статуса')),
                ('name', models.CharField(max_length=100, verbose_name='Название статуса')),
                ('is_default', models.BooleanField(default=False, verbose_name='Статус по умолчанию')),
                ('is_final', models.BooleanField(default=False, verbose_name='Финальный статус')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistic.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Статус отправки',
                'verbose_name_plural': 'Статусы отправок',
                'ordering': ['order'],
                'unique_together': {('company', 'code'), ('company', 'name')},
            },
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistic.shipmentstatus', verbose_name='Статус'),
        ),
    ]
