# Generated by Django 5.2 on 2025-04-12 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0002_shipmentstatus_alter_shipment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Код статуса')),
                ('name', models.CharField(max_length=100, verbose_name='Название статуса')),
                ('is_default', models.BooleanField(default=False, verbose_name='Статус по умолчанию')),
                ('is_final', models.BooleanField(default=False, verbose_name='Финальный статус')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_statuses', to='logistic.company')),
            ],
            options={
                'verbose_name': 'Статус заявки',
                'verbose_name_plural': 'Статусы заявок',
                'ordering': ['order', 'created_at'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistic.requeststatus', verbose_name='Статус'),
        ),
    ]
